# Generated by Django 4.2.11 on 2024-08-20 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_position_salary_max_alter_position_salary_min'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='cover_letter',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='resume',
            field=models.FileField(null=True, upload_to='resumes/'),
        ),
    ]
