# Generated by Django 4.2.11 on 2024-08-20 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_jobapplication_cover_letter_jobapplication_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='client',
            name='website',
        ),
        migrations.AlterField(
            model_name='account',
            name='user_type',
            field=models.CharField(choices=[('client', 'Client'), ('recruiter', 'Recruiter'), ('candidate', 'Candidate')], default='candidate', max_length=50),
        ),
    ]
