# Generated by Django 4.2.11 on 2024-08-20 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_client_phone_remove_client_website_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='cover_letter',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='candidate',
            name='resume',
            field=models.FileField(null=True, upload_to='resumes/'),
        ),
    ]
